name: "minify-and-purge"

on:
  push:
    branches:
      - 'main'
    paths:
      - '*.json'
      - '!*.min.json'

jobs:
  minify-and-purge:
    name: "Minify And Purge"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"

      - name: "Install Dependencies"
        run: |
          python3 -m pip install -r requirements.txt

      - name: "Minify JSON Files"
        run: |
          python3 ./.github/scripts/minify-json.py
        working-directory: ./

      - name: "Detect Changes and Commit"
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Minify JSON files."
            git push origin main
            echo "Changes committed."
          fi

      - name: "Purge jsDelivr Cache"
        run: |
          python3 ./.github/scripts/purge-jsdelivr.py
        working-directory: ./
