name: "minify-json"

on:
  push:
    branches:
      - 'main'
    paths:
      - '*.json'
      - '!*.min.json'

jobs:
  push-tag:
    name: "Minify JSON"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"

      - name: "Minify"
        run: |
          python ./.github/scripts/minify-json.py
        working-directory: ./

      - name: "Detect Changes and Commit"
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Minify JSON files."
            git push origin main
            echo "Changes committed."
          fi
